### ISSUE TITLE
Add @Vetoed to event listening classes via an AnnotationTransformer

### ISSUE THREAD

**Issue by gsmet** [quarkiverse/quarkus-github-app#109]
The event listening classes implemented by the users should not be beans because it's the subclass that should be a bean. Apparently, there is a nice `@Vetoed` annotation that should work.

We need to check (separately) how it goes with:
- a scope annotation there `@Singleton`
- also in the case of `@Startup`

With the current code, in both cases, you should have the methods called twice. We should try if adding `@Vetoed` manually fixes it.

If so, we can implement an `AnnotationsTransformer` to do it automatically. There is an example in Hibernate Validator for instance: https://github.com/quarkusio/quarkus/blob/main/extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java#L291 . The example is a bit complicated in HV, here it should be far easier: we need to push the list of event listening annotations to the transformer and add `@Vetoed` to the declaring class.

There is an additional step: the `@Startup` annotation should be copied to the generated subclass if present on the user class. We should also probably override the CDI scope of the generated subclass if a specific scope has been defined on the user class.

**Comment by gsmet** [comment]
@shinusuresh I added more information in the description. Let me know if you want to pick this one!

**Comment by shinusuresh** [comment]
@gsmet I had a look, probably a bit too much for me to take this ticket.

**Comment by gsmet** [comment]
No problem :).
