### ISSUE TITLE
Make the private key optional in tests

### ISSUE THREAD

**Issue by yrodiere** [quarkiverse/quarkus-github-app#280]
Config property `quarkus.github-app.private-key` is mandatory, but it's not really useful in dev and test mode AFAICT.

People end up setting it to a dummy private key just to make Quarkus happy.

That's inconvenient. Let's make this configuration property optional in tests and dev mode, if possible?

**Comment by gsmet** [comment]
I had a quick look at that and the private key is required for dev mode.
It can be optional only for tests.
