### ISSUE TITLE
Allow turning off reactions as command execution feedback 

### ISSUE THREAD

**Issue by lppedd** [quarkiverse/quarkus-github-app#351]
Hi everyone! First of all, amazing work on this extension.  
Now, I have a command which is quite big internally and performs a lot of checks, which then turn into a big informational message.

Even though the command may have failed, or simply aborted, the framework still react with `PLUS_ONE`.  
To avoid that, I have to throw a random exception (which is not really cool).
But still with that, a `MINUS_ONE` is used, and it could not be appropriate for the usecase.

Is there a way to completely turn off this reactions feature?

**Comment by gsmet** [comment]
Thanks! So that's indeed a good idea. I will have a look at it soon.

**Comment by lppedd** [comment]
@gsmet I think you could take two different routes:
1. Allow customizing the reaction for each type of action. As of now we have:
   ```
   ROCKET
   PLUS_ONE
   MINUS_ONE
   CONFUSED
   ```
   You could allow setting a custom reaction (`String` based) in an annotation, or in the `.properties`/`.env` file.
   An empty value means no reaction.
2. A single setting to disable everything. Then it's up to the user to add reaction through the API.

**Comment by gsmet** [comment]
I think I will keep it driven via annotations as you might want different behaviors for different commands.

I'll go for the single setting for now, and we can improve that later if we think it makes sense. The single setting would be useful anyway to disable everything in one go.

**Comment by lppedd** [comment]
Agree, let's keep it simple. Easier to implement too.

**Comment by gsmet** [comment]
I have a patch ready for that but I need to work on the testing. Should be merged by end of week latest.

**Comment by lppedd** [comment]
Thank you!
In the meantime, I was thinking how to handle the "running" state (rocket reaction) when everything is turned off.
For future reference this might be ideal:
```kotlin
@Decorator
abstract class CommandDecorator : Command {
  @Inject
  @Delegate
  private lateinit var delegate: Command

  override fun run(payload: GHEventPayload.IssueComment) {
    val comment = payload.comment
    val reaction = comment.createReaction(ReactionContent.ROCKET)

    try {
      delegate.run(payload)
    } finally {
      comment.deleteReaction(reaction)
    }
  }
}

```

**Comment by gsmet** [comment]
This is already handled in my work :).

**Comment by gsmet** [comment]
1.12.0.Final is available on Maven Central.

Documentation is here: https://quarkiverse.github.io/quarkiverse-docs/quarkus-github-app/dev/commands.html#_reaction_strategy .

For your use case, I recommend you to use `ReactionStrategy.ON_PROGRESS_ON_ERROR`. It will handle the rocket and also the potential parse errors (and potential exceptions that you might not catch).

**Comment by gsmet** [comment]
@lppedd btw, it would be awesome if you could send me an email explaining your use case and what you plan to do with Quarkus GitHub App. Except if it's highly confidential, of course. My email is on my profile page. Thanks!

**Comment by lppedd** [comment]
@gsmet sure, a bit busy today but I'll get five minutes to explain what I'm doing with this extension this evening.
