### ISSUE TITLE
Command-level configuration is never taken into consideration

### ISSUE THREAD

**Issue by lppedd** [quarkiverse/quarkus-github-app#352]
As you can see the command class name is the Quarkus-created one, not the original one.  
This means `commandConfigs.getOrDefault` will always return the default one, from the `@Cli`.  
Same for `CommandPermissionConfig` or `CommandTeamConfig`.

![image](https://user-images.githubusercontent.com/19871649/188599986-c58be3b7-cb07-4119-bac4-62df50892cf6.png)

![image](https://user-images.githubusercontent.com/19871649/188600661-ff2d5c31-48af-48ea-869f-c4ac06cdb237.png)

This is pretty severe imho.

**Comment by gsmet** [comment]
@lppedd do you have a reproducer? Because I have tests for that. Now maybe the test infrastructure hides something so having a reproducer would certainly help.

**Comment by lppedd** [comment]
@gsmet Sure, I will strip my app and upload a .zip file. Let's see what happens.

**Comment by gsmet** [comment]
OK, I have a patch ready so I'll be able to check it actually fixes your issue (and hopefully add a test if it's doable).

**Comment by lppedd** [comment]
@gsmet https://drive.google.com/file/d/1CZVYncIvrhYaGKtuIog7i5tHNoJXl0UX/view?usp=sharing
Should be sufficient. Let me know when you have downloaded it.

**Comment by gsmet** [comment]
@lppedd

I downloaded the reproducer.
Question: were you experimenting in dev mode by any chance?

Because I suspect the problem is only there in dev mode and is related to some changes in the Quarkus dev mode. That's why the tests are OK. I have a fix, trying to prepare a test for it.

**Comment by lppedd** [comment]
@lppedd yup! I was in test mode, you're right.

**Comment by lppedd** [comment]
@gsmet just noticed I wrote "test mode" instead of "dev mode".
I was focusing on testing and it slipped in, sorry.

**Comment by gsmet** [comment]
1.11.1 has been released with a fix and is available on Maven Central.

Thanks for reporting the issue!
