### ISSUE TITLE
Warn when private key or webhook secret is not defined in prod mode

### ISSUE THREAD

**Issue by gsmet** [quarkiverse/quarkus-github-app#359]

**Comment by yrodiere** [comment]
FWIW the private key is a mandatory configuration property at the moment, so startup will fail if you forget about it.

At least in dev mode, I got this, and I don't see why it would be any different in prod mode:

```
One or more configuration errors have prevented the application from starting. The errors are:
  - SRCFG00014: The config property quarkus.github-app.private-key is required but it could not be found in any config source
```

Related: #280
