### ISSUE TITLE
Wrap in backticks the command in case of internal parse errors

### ISSUE THREAD

**Issue by lppedd** [quarkiverse/quarkus-github-app#373]
Follow up to #366.

Outputting the original command as code avoids a tag and it's also easier to read.
In the following case the error message comes from an exception. A simple `replace` should work imo.

![image](https://user-images.githubusercontent.com/19871649/191066682-3ddcbc4e-b534-42cb-a65f-6cd9871e931d.png)

In my case I've got a customized error message, using
```
parseErrorStrategy = ParseErrorStrategy.COMMENT_MESSAGE_HELP_ERRORS,
parseErrorMessage = "> `%s`\n\n:warning: Unable to parse the command.",
```
So don't mind the duplication.

**Comment by lppedd** [comment]
Btw, the outputted help content is too generic, so it's also unnecessary in this case.  
I don't know if there is way to output a the actual command help.

**Comment by gsmet** [comment]
> Btw, the outputted help content is too generic, so it's also unnecessary in this case.

There's no way to make it more specific given we were unable to parse the message, I will just remove it.

I like your output, I will make it the default and also get rid of the command in the unbalanced quotes error as it's redundant.

**Comment by lppedd** [comment]
@gsmet 

> There's no way to make it more specific given we were unable to parse the message, I will just remove it.

Sounds perfect for this kind of errors.

> I like your output

Before you merge the PR, consider my current convention (the screenshot a couple days old).
Errors: `:rotating_light:` 🚨 
Warnings: `:warning:` ⚠️ 
Info: `:loudspeaker:` 📢 

So this would be 🚨 
Well seems like I wasn't fast enough 🤣

**Comment by gsmet** [comment]
Ah yeah, I struggled to find a nice error icon but yours is a good proposal. I'll update it and it can go in the next release.

**Comment by gsmet** [comment]
Adjusted and I shipped another release while at it. So 1.13.2 should hit Central soon with all the changes.

Thanks for the suggestions!

**Comment by gsmet** [comment]
@allcontributors add lppedd for bugs
