### ISSUE TITLE
Deploy serverless GitHub bot

### ISSUE THREAD

**Issue by nragon** [quarkiverse/quarkus-github-app#395]
Hi,
Any example on how to deploy [this](https://quarkus.io/guides/amazon-lambda) using, for instance, lambda + api gateway on aws?
Would this extension help? Maybe with an forwarder like [smee](https://github.com/quarkiverse/quarkus-github-app/blob/main/runtime/src/main/java/io/quarkiverse/githubapp/runtime/smee/SmeeIoForwarder.java)

Thanks,
Nuno

**Comment by gsmet** [comment]
Hi Nuno,

I totally agree GitHub Apps are very good candidates for lambdas.

I haven't really had the opportunity to play with lambdas though. If someone wants to experiment with it, I will be happy to answer questions and provide guidance.

**Comment by nragon** [comment]
@gsmet 
I'll give it a try. I think using lambda-http plugin will work.
Thank you.

**Comment by gsmet** [comment]
Please report back and, if possible, create a PR for the doc to explain how to set it up.

Thanks!
