### ISSUE TITLE
GitHub object mock

### ISSUE THREAD

**Issue by nragon** [quarkiverse/quarkus-github-app#399]
Hi,
Currently there's no way to mock GitHub instance when injected like this: https://quarkiverse.github.io/quarkiverse-docs/quarkus-github-app/dev/developer-reference.html#_injecting_a_github_instance

This will be helpful to getRepository("X") or getOrganization("Y")

Ideally we should be able to access a GitHub mock within `given().github(mocks -> when(mock.getClient().getOrganization("Y").thenReturn(...)`

**Comment by yrodiere** [comment]
Hi,

Doesn't this work?

```
given().github(mocks -> {
    GHOrganization orgMock = mocks.ghObject(GHOrganization.class, 42);
    when(mock.installationClient(<your installation ID>).getOrganization("Y")).thenReturn(orgMock);
});
```

**Comment by yrodiere** [comment]
@nragon Bump. Does my suggestion work?

**Comment by gsmet** [comment]
Closing as I think @yrodiere's suggestion solves the original issue.
