### ISSUE TITLE
Can't get GraphQL and RestClient at the same time for GHE

### ISSUE THREAD

**Issue by kanimaru** [quarkiverse/quarkus-github-app#413]
Hi I'm using <quarkus-github-app.version>1.15.2</quarkus-github-app.version>
and have trouble with getting both clients (cause of legacy reasons I need both)

For the RestClient I need an URL like: _https://github.example.com/api/v3_
But then the graphsql respons with a REST error message:
```
InvalidResponseException: Unexpected response. Code=404, message="Not Found", body="{"message":"Not Found","documentation_url":"https://docs.github.com/enterprise/3.5/rest"}"
```
Cause it tries to use _https://github.example.com/api/v3/graphql_

But when I try one of this:
_https://github.example.com/api/_
_https://github.example.com/_
_https://github.example.com_

The Rest API cries with a generic _org.kohsuke.github.HttpException_ 

Any Ideas?

**Comment by gsmet** [comment]
It's hard to know with the information you provided? Any chance you could put together a small reproducer?

My guess is that if it doesn't work with your setup, it will probably not work if you try with the standard GitHub instance and I will be able to see what's going on.

**Comment by kanimaru** [comment]
![image](https://media.giphy.com/media/uWlpPGquhGZNFzY90z/giphy.gif)

**Comment by gsmet** [comment]
Thanks for the details.

Quarkus GitHub App 1.16.0 is on its way to Maven Central, it should be available in ~30 minutes.

You will have two new properties to define separately the REST API endpoint and the GraphQL API endpoint:

- `quarkus.github-app.rest-api-endpoint`
- `quarkus.github-app.graphql-api-endpoint`

I think it should fix your issue.
