### ISSUE TITLE
Updating a release to latest.

### ISSUE THREAD

**Issue by PedroQGomes** [quarkiverse/quarkus-github-app#421]
Hi, I'm having trouble updating a release to the latest with the GHReleaseUpdater class. Is there a way I can do it?

If not, is it possible to get the auth token from GitHub class or GitHubService class, so I can make a curl request to the GitHub API directly?

Thanks in advance.

**Comment by gsmet** [comment]
Sorry for the delay. Could you describe the issue you had?
