### ISSUE TITLE
need help to access project v2

### ISSUE THREAD

**Issue by moglideveloper** [quarkiverse/quarkus-github-app#423]
Wonderful project for writing git-apps in java.

Trying to figure out, how to access projects v2 (beta) using API.

There is no example available in the docs.

https://quarkiverse.github.io/quarkiverse-docs/quarkus-github-app/dev/index.html

not much help available on internet for accessing projects v2(beta) using `quarkus-github-app`

will be helpful, if we have some example for projects v2

A very basic example will help others to understand API better.
For example : **addding a new issue to project board**

**Comment by gsmet** [comment]
The projects v2 REST API is very cumbersome and not very practical. I recommend using the GraphQL API instead. 

You can find an example here: https://github.com/quarkusio/quarkus-github-bot/blob/main/src/main/java/io/quarkus/bot/PushToProjects.java
