### ISSUE TITLE
Failing mvn setup

### ISSUE THREAD

**Issue by Solido** [quarkiverse/quarkus-github-app#441]
First **Hi** and **thank you** for this plugin!

I'm trying to setup a project following mvn:

 ```
 mvn io.quarkus:quarkus-maven-plugin:2.16.2.Final:create \
    -DprojectGroupId=app.name \
    -DprojectArtifactId=name-gh-app \
    -Dextensions="io.quarkiverse.githubapp:quarkus-github-app:1.16.0" \
    -DnoCode
```

But both Quarkus 2 and 3 alpha fail with

`[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.16.2.Final:create (default-cli) on project standalone-pom: Execution default-cli of goal io.quarkus:quarkus-maven-plugin:2.16.2.Final:create failed: A required class was missing while executing io.quarkus:quarkus-maven-plugin:2.16.2.Final:create: org/eclipse/aether/connector/basic/BasicRepositoryConnectorFactory`

Using mvn 3.9.0 on mac.

Best regards

**Comment by gsmet** [comment]
Yeah there is a small compatibility issue between Quarkus and Maven 3.9.0, we are working on it (it's a problem with the Quarkus Maven Plugin itself).

For the meantime, stick to 3.8: https://archive.apache.org/dist/maven/maven-3/3.8.7/binaries/ and everything should work fine.

/cc @aloubyansky FYI

**Comment by Solido** [comment]
Merci @gsmet!
