### ISSUE TITLE
Mvn boostrap fail to compile

### ISSUE THREAD

**Issue by Solido** [quarkiverse/quarkus-github-app#442]
Setting up a mvn with 1.16 fail to compile with
ClassNotFound `io/smallrye/common/annotation/RunOnVirtualThread`

2.0.0.Alpha1 fail with `jakarta.enterprise.event.Event` ClassNotFound.

Thanks!

**Comment by gsmet** [comment]
2.0.0.Alpha1 is to be used with Quarkus 3.0.0.Alpha4 so you probably don't want to go there.

As for 1.16.0, make sure you use the latest Quarkus 2.16 and that the Quarkus Maven Plugin version is consistent with the Quarkus BOM version.

I just tried to create a project using the command line that is there: https://quarkiverse.github.io/quarkiverse-docs/quarkus-github-app/1.x/create-github-app.html  and the project compiles fine.

**Comment by Solido** [comment]
Don't know where copy-pasted the wrong version for 2.16.
All is in place right now!!
Special thanks for the quick help Guillaume.

**Comment by gsmet** [comment]
Happy to hear that. Have fun!
