### ISSUE TITLE
GitHubAppMockito in the documentation 1.x is not existing

### ISSUE THREAD

**Issue by kanimaru** [quarkiverse/quarkus-github-app#463]
https://quarkiverse.github.io/quarkiverse-docs/quarkus-github-app/1.x/testing.html#_more_advanced_mockito_features in the second code snippet there is a Class called `GitHubAppMockito` that doesn't exists in 1.16 lib. 
Seems it came with Version 2.x?

**Comment by gsmet** [comment]
You're right, it has been merged and never released (and the doc is based on the content of the branch).

I'm pushing a 1.17.0 right now with what is currently on the 1.x branch.

**Comment by gsmet** [comment]
Release done, it should hit Maven Central in ~20 minutes.
