### ISSUE TITLE
Allow to retrieve file from Pull Request directly

### ISSUE THREAD

**Issue by The-Huginn** [quarkiverse/quarkus-github-app#486]
Currently to retrieve proposed file changes I retrieve a file from `main` branch and then apply a patch. However I can see an API endpoint URL for the proposed changed file under `GHPullRequestFileDetail#getRawUrl`. It would be great to directly retrieve the contents of the file using similar approach to `GitHubConfigFileProvider#fetchConfigFile` or at least as a `String`.

This would be probably needed to be propagated to https://github.com/hub4j/github-api to keep the authorization in one place.

Pardon me if this is already possible.

**Comment by gsmet** [comment]
Hi @The-Huginn ,

I started having a look at this and coded something until I realized just injecting a `GitHub` instance in your listening method would be nearly as good.

If you add a `GitHub gitHub` parameter to your method, you will get an authenticated client injected. And then you can get the content of the file via `gitHub.getRepository(repository).getFileContent(path, ref)`.

I think something like the following would work:
```java
gitHub.getRepository(pullRequest.getHead().getRepository().getFullName())
                .getFileContent("your path", pullRequest.getHead().getSha());
```

Let me know how it goes for you.

**Comment by The-Huginn** [comment]
Hi @gsmet , yes, it is exactly what I was looking for. Thanks for that & sorry for late response.
