### ISSUE TITLE
Dev UI - provide link to Replay UI from the GitHub App tile

### ISSUE THREAD

**Issue by rsvoboda** [quarkiverse/quarkus-github-app#627]
Dev UI - provide link to Replay UI from the GitHub App tile

One needs to find out about http://localhost:8080/replay/ URL from the docs.

GitHub App tile in Dev console could use inspiration from SmallRye Health
<img width="321" alt="Screenshot 2024-06-18 at 23 35 02" src="https://github.com/quarkiverse/quarkus-github-app/assets/925259/cf29721a-8d68-4276-b4eb-07e3f8d06063">
<img width="321" alt="Screenshot 2024-06-18 at 23 36 47" src="https://github.com/quarkiverse/quarkus-github-app/assets/925259/c479e95d-2ddc-4f25-84ea-b72cd3f64b29">

**Comment by gsmet** [comment]
@melloware wondering if you would be interested in helping here? :)

**Comment by melloware** [comment]
I can do this if you assign it to me.

**Comment by gsmet** [comment]
I was wondering if at some point it would make sense to implement the Replay UI as an integral part of the Dev UI but I'm not sure it's worth the hassle given we have something simple and working (but with an old version of Vue).

Having a simple link to `/replay` is a good first step IMO.

Feedback welcome.

**Comment by rsvoboda** [comment]
+1 to add link for now

Rework into DevUI would give better experience, I understand it's a lot of work because different front-end framework is used, etc. We should probably come up with other reasons to rework this :) But I have just the "unified experience" topic.

From pure Quarkus dev side, it could be good experiment to see how hard it is to maintain external component for DevUI :)

**Comment by melloware** [comment]
I know this may be a dumb question but is there a way to run `mvn quarkus:dev` without needing all the setup in the startup guide just so I can test?  If not i may build this card blind and have you guys test it if that is OK?

**Comment by gsmet** [comment]
@melloware I think having the following in the application.properties should be enough:

```
quarkus.github-app.app-id=0
quarkus.github-app.private-key=-----BEGIN RSA PRIVATE KEY-----\
MIIEogIBAAKCAQEA30YvyuZAd+kGDT0nm/XAa93CqsDvC/iYOc4KsKsfBQs1MWjH\
royuVDfQj2fJvueFnOgZApM3viaCz188D/j3tUMNByIKOfMLiEm/R1tqe7Q6xRRn\
uwpfT+wv+/x4cNvPxTscwo43LVR9Pno71UfZZywnYN03GS71ttNCiiBKXwCSnHez\
/t79iAmMnym7ViNsKzA0aS5EwAw9A3GeTnxpRef0y0vDNE2aXBNCe+f1ZnFq1Fhe\
PJIlKs/qlM136A2co+WRaPghacZJMuwQr1vajuMSBjMEroIPOfSG3x3Oitvnukjp\
EwuhXjmZeaLc+60rYaMRwf+bje8KmaAVOMWkHQIDAQABAoIBAA+d8SnYARpiCjJS\
3Lpj7hmdYUhgRlgoAz3H06eX0IuhxQ63rX/gBzGM1eGx+MKJnybidR1g/r0mJHAs\
0R6s42aiUf71upFjFqNpxR9QnZoZeSLf0oGasB/+/Tw65JHATkAVamWRXPqmtjvw\
gM7iP6qfxAFad8gjKLyo+jZ/G7SZTCMwnp+sRynirNpycxaAn/xK6Pe43+nyQVWT\
E0J8bvCzrFD47CM5zZaBQlLWTMjY4Rr3U6BMTGwQWJzGkeGn+2JsHVUch0k7+NRa\
e3FKjT+57dZqQTnGPVSpBFWEXVO9KLEuLBLyRx0348TZBHzIM9IigN4QS2AaWTJw\
1kp3VWECgYEA/3P/nsL+RL/yqYvENZ7XqEkXRNH6YHOe8h/lFoYHStCl9y0T8O+z\
ooJq9hEq7QcYs2bHvBWj8B9he7+bZ5ZOMAM6oIgrgB5FzSvL7JzXhEdONxe/j2TI\
GbQuC+NxdJtx4Y6yF9Lrb1UyKX+HzR4de+v6b5hER7x8x4gQn1sCYmsCgYEA38CN\
bTtE3RKY98m33a1Cd6hNXHSyy5GOK5/XGDn0XoGfFe5YJnnh2lia2V4xqUH9d1Mu\
bB0bEUhfbac5SX5SIW+NBVxzehqfMkrZj/rzN8Wd7TrYAHSldSMhkPTuwuuzfnHL\
sJLe2gyoqq+sooeE7eCH2fpPIN0wg5U+jc60hZcCgYBHtmrGSPtUlYYr7p6wZt0n\
0w0DNudQ+GRgmG+ZeRrG9/f/gdodQ01si6w3U+53CAz5IBtmQ7T4Dfcx5EJePCXK\
+L0Wn+OGXfk+ddMTo5wk+FeOw831FVfPT3O1xq3tDE5WAdchNQb/BC3G1JRtEs04\
IrD1bwuMD+//m8T+12+97QKBgDko0XhEGdV3+MfkKiphJoe24Pxre3lxl6YhUSuJ\
Mpop9t/9YVuC62WCGRzKaVlZ2ExxXXyU+uMxX999Rq81q/mKq7Xg5kcdIeoRIP8d\
FqD6xNtjmuaS5enErcCAMbZtzA7TNzvGaVO+xB/GfQ2QHS8/mrTesvQsTUZwC+ji\
E0/FAoGATJvuAfgy9uiKR7za7MigYVacE0u4aD1sF7v6D4AFqBOGquPQQhePSdz9\
G/UUwySoo+AQ+rd2EPhyexjqXBhRGe+EDGFVFivaQzTT8/5bt/VddbTcw2IpmXYj\
LW6V8BbcP5MRhd2JQSRh16nWwSQJ2BdpUZFwayEEQ6UcrMfqvA0=\
-----END RSA PRIVATE KEY-----
```

If not, yeah, push a PR and I'll have a look.

**Comment by melloware** [comment]
thanks let me try

**Comment by melloware** [comment]
PR submitted but here is what is strange.  The Replay UI is not available in Dev Mode?  Its only available in NON Dev mode so the link goes no where but to a 404.
