### ISSUE TITLE
Allow Github Event ruoting to serve on HTTP Paths other than root

### ISSUE THREAD

**Issue by ryandens** [quarkiverse/quarkus-github-app#629]
Currently, this extension listens for GitHub Events on the root path of the HTTP server. This is expressed in two locaitons that I'm aware of 
- the Vertx route registration: https://github.com/quarkiverse/quarkus-github-app/blob/main/runtime/src/main/java/io/quarkiverse/githubapp/runtime/Routes.java#L75C1-L75C141
- The Smee forwarder: https://github.com/quarkiverse/quarkus-github-app/blob/main/runtime/src/main/java/io/quarkiverse/githubapp/runtime/smee/SmeeIoForwarder.java#L53

I would like to serve this listener from my application which is a GitHub app but also serves other HTTP requests, and the root path of the application is already spoken for. Ideally, i'd like to configure this extension to listen on `/github-event`, which is where my own GitHub event routing listens currently, but i think it's sensible to allow for any path to be configured. I think this will help those who would like to migrate to this extension an easier path to do so because they may not follow the conventions laid out in this extension.

The `Routes` class would have to programmatically register the route via an injected vertx router rather than via the `@Route` annotation, but it seems relatively straightforward.

If you're open to the change, I'd be happy to make a PR to contribute it.

**Comment by gsmet** [comment]
It perfectly makes sense.

I must admit that I always saw a GitHub App as run separately but it makes perfect sense to be more friendly with additional features.

Even better if you provide a PR :).

**Comment by ryandens** [comment]
Thanks! We initially also ran it as a separate app but are now seeing benefits from deploying it as part of a more modular monolith.
