### ISSUE TITLE
Have a static GET endpoint with an index.html

### ISSUE THREAD

**Issue by gsmet** [quarkiverse/quarkus-github-app#634]
When your app is up, it's hard to actually test it because all you get is a `POST` endpoint.

I think it would be a good idea to have an index.html on `GET` that would be:

- a white page
- with the Quarkus GitHub App logo (https://camo.githubusercontent.com/8a5f2c33d612247e9f9df214f99af384f7b04fba06ea67e1cc6a2454889e1716/68747470733a2f2f64657369676e2e6a626f73732e6f72672f717561726b75732f626f742f66696e616c2f696d616765732f717561726b7573626f745f66756c6c2e737667) centered (ideally horizontally and vertically). Let's not make the logo too big :). You can find a bunch of formats here: https://design.jboss.org/quarkus/ (look for `bot` - there are 3 versions, full body would have  my preference, unless we can do something fancy with the others)

**Comment by lppedd** [comment]
In my case I had long set up a GET endpoint that simply returns `Your GitHub App is running!`.  
I've done the same in all my apps.
