### ISSUE TITLE
Throw an error if the event listening class is annotated with `@Startup`

### ISSUE THREAD

**Issue by gsmet** [quarkiverse/quarkus-github-app#90]
If a class is annotated with `io.quarkus.runtime.Startup`, it will be made a bean.

We do not want the event listening class to be a bean as it will be subclassed and it's the subclass that should be a bean.

Typically, this can lead to unexpected behavior when having a `@PostConstruct` annotation.

**Comment by shinusuresh** [comment]
Hi @gsmet I would like to take a look on this issue. 

Is this the class and method to do the check

https://github.com/quarkiverse/quarkus-github-app/blob/main/deployment/src/main/java/io/quarkiverse/githubapp/deployment/GitHubAppProcessor.java#L264

Is it an IllegalArgumentException to be thrown if the annotation is found?

**Comment by gsmet** [comment]
Hi @shinusuresh .

Yeah that would have been the class.

But I think what we should do instead to solve this issue is implement https://github.com/quarkiverse/quarkus-github-app/issues/109 . It should solve the problem in a far better way.

I'll add some information to #109 so that you have some guidance.

Will close this one!
